# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from palace.grpc._generated import palace_pb2 as palace__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in palace_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryServiceStub(object):
    """-- Service ----------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMemory = channel.unary_unary(
                '/palace.v1.MemoryService/CreateMemory',
                request_serializer=palace__pb2.CreateMemoryRequest.SerializeToString,
                response_deserializer=palace__pb2.MemoryResponse.FromString,
                _registered_method=True)
        self.GetMemory = channel.unary_unary(
                '/palace.v1.MemoryService/GetMemory',
                request_serializer=palace__pb2.GetMemoryRequest.SerializeToString,
                response_deserializer=palace__pb2.MemoryResponse.FromString,
                _registered_method=True)
        self.DeleteMemory = channel.unary_unary(
                '/palace.v1.MemoryService/DeleteMemory',
                request_serializer=palace__pb2.DeleteMemoryRequest.SerializeToString,
                response_deserializer=palace__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.SearchMemories = channel.unary_unary(
                '/palace.v1.MemoryService/SearchMemories',
                request_serializer=palace__pb2.SearchMemoriesRequest.SerializeToString,
                response_deserializer=palace__pb2.SearchMemoriesResponse.FromString,
                _registered_method=True)
        self.ListMemories = channel.unary_unary(
                '/palace.v1.MemoryService/ListMemories',
                request_serializer=palace__pb2.ListMemoriesRequest.SerializeToString,
                response_deserializer=palace__pb2.ListMemoriesResponse.FromString,
                _registered_method=True)


class MemoryServiceServicer(object):
    """-- Service ----------------------------------------------------------

    """

    def CreateMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchMemories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMemories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMemory,
                    request_deserializer=palace__pb2.CreateMemoryRequest.FromString,
                    response_serializer=palace__pb2.MemoryResponse.SerializeToString,
            ),
            'GetMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemory,
                    request_deserializer=palace__pb2.GetMemoryRequest.FromString,
                    response_serializer=palace__pb2.MemoryResponse.SerializeToString,
            ),
            'DeleteMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMemory,
                    request_deserializer=palace__pb2.DeleteMemoryRequest.FromString,
                    response_serializer=palace__pb2.DeleteResponse.SerializeToString,
            ),
            'SearchMemories': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchMemories,
                    request_deserializer=palace__pb2.SearchMemoriesRequest.FromString,
                    response_serializer=palace__pb2.SearchMemoriesResponse.SerializeToString,
            ),
            'ListMemories': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMemories,
                    request_deserializer=palace__pb2.ListMemoriesRequest.FromString,
                    response_serializer=palace__pb2.ListMemoriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'palace.v1.MemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('palace.v1.MemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryService(object):
    """-- Service ----------------------------------------------------------

    """

    @staticmethod
    def CreateMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/palace.v1.MemoryService/CreateMemory',
            palace__pb2.CreateMemoryRequest.SerializeToString,
            palace__pb2.MemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/palace.v1.MemoryService/GetMemory',
            palace__pb2.GetMemoryRequest.SerializeToString,
            palace__pb2.MemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/palace.v1.MemoryService/DeleteMemory',
            palace__pb2.DeleteMemoryRequest.SerializeToString,
            palace__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchMemories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/palace.v1.MemoryService/SearchMemories',
            palace__pb2.SearchMemoriesRequest.SerializeToString,
            palace__pb2.SearchMemoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMemories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/palace.v1.MemoryService/ListMemories',
            palace__pb2.ListMemoriesRequest.SerializeToString,
            palace__pb2.ListMemoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
